#!/usr/bin/perl


use Time::Local;

my $basePath;
my %apDict;

BEGIN{
    sub getFromRc(){
        my $file = @_[0];
        my %rcDict;
        open(F, "<$file");
        while(<F>){
            if(/^#/ or /^$/){ next; }
            chop;
            if(/=/){
                ($key, $value) = split(/=/,$_,2);
                $rcDict{$key} = "$value";
            }
        }
        close(F);
        return %rcDict;
    }
    
    my $home = $ENV{HOME};
    my $rcfile = "$home/.automatedProcessing";
    if(!-e $rcfile){
        die "Please run AP_assistant at least once.\n";
    }
    %apDict = &getFromRc($rcfile);
    $basePath = $apDict{"basePath"};
}

#use timex qw(&dateToDoy &isLeap &daysInMonth &daysInYear &listOfDates
#&datesBetween &segmentedDates);

use lib "$basePath/SOFTWARE/SCRIPTS/AUTOMATED_PROCESSING";
use ap_timex;

if($#ARGV < 0){
    die "Usage:  test_timex.pl valid-date-string\n\n";
}

$dateString = shift(@ARGV);

@lod = &getListOfDates($dateString);

foreach $_ (@lod){
    print "$_\n";
}

